Infostrait.Azzysa.Import.UI/Controllers/SmarTeamController.cs
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Data.OleDb;
using System.IO;
using System.Linq;
using System.Web.Mvc;
using System.Xml.Serialization;
using Hangfire;
using Infostrait.Azzysa.Import.UI.Components;
using System.Diagnostics;
using System.Text;
using System.Web.Http;
using Infostrait.Azzysa.Batch.Kernel;
using Infostrait.Azzysa.Import.ENOVIA.SmarTeam;
using Newtonsoft.Json;
using Newtonsoft.Json.Serialization;
using Plugin = Infostrait.Azzysa.Import.ENOVIA.Plugin;

namespace Infostrait.Azzysa.Import.UI.Controllers
{
    public class SmarTeamController : Controller
    {

        public ActionResult Index()
        {
            // Get SmarTeam database name
            try
            {
                ViewBag.DataBaseName =
                    ENOVIA.SmarTeam.Plugin.GetSmarTeamDataBaseName(
                        AzzysaBootstrapper.GetBootstrapper.GetKernelContext()
                            .GetRuntime()
                            .SettingsProvider.GetSettingValue("SmarTeam.ConnectionString")
                            .Replace(Plugin.ConnStringPrefixSmarteam,
                                string.Empty));

                // Get all SmarTeam classes
                var allClasses = ENOVIA.SmarTeam.Plugin.GetSmarTeamClasses(
                    AzzysaBootstrapper.GetBootstrapper.GetKernelContext()
                        .GetRuntime()
                        .SettingsProvider.GetSettingValue("SmarTeam.ConnectionString")
                        .Replace(Plugin.ConnStringPrefixSmarteam,
                            string.Empty), new List<string>());

                // Return view based on top level classes
                return View(allClasses);

            }
            catch (ApplicationException ex)
            {
                // Show error
                ViewBag.DataBaseName = ex.Message;

                // Get all SmarTeam classes
                var allClasses = new List<SmarTeamClass>();

                // Return view based on top level classes
                return View(allClasses);

            }
        }

        public ActionResult ClassDetails(string className)
        {
            // Get the SmarTeam class object
            var smarTeamClass = ENOVIA.SmarTeam.Plugin.GetSmarTeamClasses(
                AzzysaBootstrapper.GetBootstrapper.GetKernelContext().GetRuntime().SettingsProvider.GetSettingValue("SmarTeam.ConnectionString").Replace(Plugin.ConnStringPrefixSmarteam, 
                string.Empty), new List<string>() {className}).FirstOrDefault();

            // Initialize context and get attribute and command information
            var classAndAttributes = ENOVIA.SmarTeam.Plugin.GetSelectCommandAndAttributes(
                new OleDbConnection(AzzysaBootstrapper.GetBootstrapper.GetKernelContext().GetRuntime().SettingsProvider
                .GetSettingValue("SmarTeam.ConnectionString").Replace(Plugin.ConnStringPrefixSmarteam, string.Empty)), smarTeamClass, null, new List<string>());
            var initializationCommand =
                ENOVIA.SmarTeam.Plugin.GetInitializationCommand(
                    AzzysaBootstrapper.GetBootstrapper.GetKernelContext().GetRuntime().SettingsProvider.GetSettingValue("SmarTeam.ConnectionString")
                    .Replace(Plugin.ConnStringPrefixSmarteam, string.Empty), smarTeamClass);

            // Return the requested view
            ViewBag.CommandText = classAndAttributes.Key.CommandText;
            ViewBag.InitializationCommand = initializationCommand.CommandText;
            ViewBag.ClassName = className;
            return View(classAndAttributes.Value);
        }

        public JsonResult GetInitializationCommand(string className)
        {
            // Get the SmarTeam class object
            var smarTeamClass = ENOVIA.SmarTeam.Plugin.GetSmarTeamClasses(
                AzzysaBootstrapper.GetBootstrapper.GetKernelContext().GetRuntime().SettingsProvider.GetSettingValue("SmarTeam.ConnectionString").Replace(Plugin.ConnStringPrefixSmarteam,
                string.Empty), new List<string>() { className }).FirstOrDefault();

            // Initialize context and get attribute and command information
            return Json(ENOVIA.SmarTeam.Plugin.GetInitializationCommand(
                    AzzysaBootstrapper.GetBootstrapper.GetKernelContext().GetRuntime().SettingsProvider.GetSettingValue("SmarTeam.ConnectionString")
                    .Replace(Plugin.ConnStringPrefixSmarteam, string.Empty), smarTeamClass).CommandText); 
        }

        public JsonResult GetDetailsCommand(string className)
        {
            // Get the SmarTeam class object
            var smarTeamClass = ENOVIA.SmarTeam.Plugin.GetSmarTeamClasses(
                AzzysaBootstrapper.GetBootstrapper.GetKernelContext().GetRuntime().SettingsProvider.GetSettingValue("SmarTeam.ConnectionString").Replace(Plugin.ConnStringPrefixSmarteam,
                string.Empty), new List<string>() { className }).FirstOrDefault();

            // Initialize context and get attribute and command information
            return Json(ENOVIA.SmarTeam.Plugin.GetSelectCommandAndAttributes(
                new OleDbConnection(AzzysaBootstrapper.GetBootstrapper.GetKernelContext().GetRuntime().SettingsProvider
                .GetSettingValue("SmarTeam.ConnectionString").Replace(Plugin.ConnStringPrefixSmarteam, string.Empty)), smarTeamClass, null, new List<string>()).Key.CommandText);
        }

        public FileResult DownloadPackage(string className, string packageId, string attributeFilter)
        {
            // Parse attribute filter
            var attributeList = new List<string>();
            if (!string.Equals("attribute filter".ToLower(), attributeFilter.ToLower()) && !string.IsNullOrWhiteSpace(attributeFilter))
            {
                attributeList = attributeFilter.Split(new char[] {Char.Parse(",")}, StringSplitOptions.RemoveEmptyEntries).ToList();
            }

            // Use the following only to create a local cache in for this class case that didn't yet exist:
            Infostrait.Azzysa.Import.ENOVIA.SmarTeam.Plugin.GetInitializationCommand(Plugin.ConnStringPrefixSmarteam + AzzysaBootstrapper.GetBootstrapper.GetKernelContext().GetRuntime().SettingsProvider.GetSettingValue("SmarTeam.ConnectionString"),
                className);
            Infostrait.Azzysa.Import.ENOVIA.SmarTeam.Plugin.GetInitializationCommand(Plugin.ConnStringPrefixSmarteam + AzzysaBootstrapper.GetBootstrapper.GetKernelContext().GetRuntime().SettingsProvider.GetSettingValue("SmarTeam.ConnectionString"),
                className,"1"); // "1" as packagefilter is a dummy, just to generate cache command...

            // Get package details
            var package =
                (new Plugin()).GetObjectDetails(
                    Plugin.ConnStringPrefixSmarteam + AzzysaBootstrapper.GetBootstrapper.GetKernelContext().GetRuntime().SettingsProvider.GetSettingValue("SmarTeam.ConnectionString"),
                    packageId, className, attributeList);

            // Return serialized package if retrieved
            if (package != null)
            {
                package.MappingReference = $"azzysa.ef.{className.ToLower().Replace(" ", string.Empty)}";

                // Convert to JSON string
                //PKA: Changed the serializer so that decimals are written with decimal places only if it's not a whole number
                var serializer = new Newtonsoft.Json.JsonSerializer();
                serializer.Converters.Add(new WholeNumberJsonConverter());

                var sb = new StringBuilder();
                var writer = new JsonTextWriter(new StringWriter(sb));
                writer.Indentation = 4;
                writer.Formatting = Formatting.Indented;

                // Web API configuration and services
                serializer.Serialize(writer, package);
                serializer.ContractResolver = new CamelCasePropertyNamesContractResolver();
                var content = sb.ToString();
                var packageBytes = System.Text.Encoding.UTF8.GetBytes(content);

                // Return the file object
                var filename = packageId.Contains(",") ? packageId.Substring(0, (packageId.Length > 20 ? 20 : packageId.Length)) : packageId;
                return File(packageBytes, System.Net.Mime.MediaTypeNames.Application.Octet, filename + ".json");
            }
            else
            {
                throw new ApplicationException("Invalid package id");
            }
        }

        [System.Web.Mvc.HttpPost]
        public JsonResult ProcessPackageAsync(string className, string configurationName, string packageId)
        {
            // Create event log source
            if (!EventLog.SourceExists("azzysa")) { EventLog.CreateEventSource(new EventSourceCreationData("azzysa", "azzysa")); }

            // Instantiate ENOVIA plugin
            EventLog.WriteEntry("azzysa", "Instantiate ENOVIA plugin", EventLogEntryType.Information);
            var plugin = new Plugin();

            // Log information
            EventLog.WriteEntry("azzysa", string.Format("Start migrate package '{0}' in class '{1}' to queue...'", packageId, className), EventLogEntryType.Information);

            // Get package size
            var configuredPackageSize = ConfigurationManager.AppSettings["Azzysa.Import.PackageSize"];
            var packageSize = string.IsNullOrWhiteSpace(configuredPackageSize) ? 150 : int.Parse(configuredPackageSize);

            // Initialize queue connector
            var queueConnector = new WebQueueImplementation();

            // Start the import process
            plugin.Initialize(Plugin.ConnStringPrefixSmarteam + AzzysaBootstrapper.GetBootstrapper.GetKernelContext().GetRuntime().SettingsProvider.GetSettingValue("SmarTeam.ConnectionString")

Infostrait.Azzysa.Import.UI/Views/SmarTeam/ClassDetails.cshtml
@using System.Web.UI.WebControls.Expressions
@model Dictionary<String, String>

@{
    ViewBag.Title = ViewBag.ClassName + " - Details";
}

<h2>Attribute information for '@ViewBag.ClassName'</h2>

<h3>Initialization command:</h3>
<div style="overflow: scroll; height: 6vh;">
    @ViewBag.InitializationCommand
</div>

<h3>Package details command:</h3>
<div style="overflow: scroll; height: 10vh;">
    @ViewBag.CommandText
</div>

<h3>Package details:</h3>
<div style="overflow: scroll; height: 10vh;">
    <table class="table">
        <tr>
            <th>
                Select clause (in select command)
            </th>
            <th>
                Exposed as (in the data package)
            </th>
        </tr>

        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Key)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Value)
                </td>
            </tr>
        }
    </table>
</div>


<div style="overflow: scroll; height: 30vh;">
    @using (Html.BeginForm("DownloadPackage", "SmarTeam", FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
    {
        <h3>Download package object:</h3>
        @Html.AntiForgeryToken()
        <div class="form-group">
            @Html.Hidden("className", (string)(ViewBag.ClassName))
            <div class="col-md-10">
                @Html.Label("Provide attribute filter and package id", new { @class = "col-md-2 control-label" })
                @Html.TextBox("attributeFilter", "attribute filter", new { width = "200px;" })
                @Html.TextBox("packageId", "package id")
                <input type="submit" class="btn btn-default" value="Download Package"/>
            </div>
        </div>
    }
    @using (Html.BeginForm("ProcessPackageAsync", "SmarTeam", FormMethod.Post, new { @class = "form-horizontal", role = "form", target = "_blank" }))
    {
        <h3>Process package object:</h3>
        @Html.AntiForgeryToken()
        <div class="form-group">
            @Html.Hidden("className", (string)(ViewBag.ClassName))
            <div class="col-md-10">
                @Html.Label("Provide package id", new { @class = "col-md-2 control-label" })
                @Html.TextBox("packageId", "package id")
                @Html.TextBox("configurationName", "azzysa.ef." + ((string)(ViewBag.ClassName)).ToLower().Replace(" ", string.Empty))
                <input type="submit" class="btn btn-default" value="Process Package"/>
            </div>
        </div>
    }
</div>

Infostrait.Azzysa.Import.UI/Views/SmarTeam/Index.cshtml
@using System.Web.UI.WebControls.Expressions
@model IEnumerable<Infostrait.Azzysa.Import.ENOVIA.SmarTeam.SmarTeamClass>

@{
    Layout = null;
    ViewBag.Title = "SmarTeam";
}

<h3>@ViewBag.DataBaseName</h3>

<script type="text/javascript">

    function ShowCommands(className) {
        $('#CommandModalLabel').html(className + ' | Commands');

        //var serviceUrl = '/SmarTeam/GetInitializationCommand';
        var serviceUrl = '@Url.Content("~/SmarTeam/GetInitializationCommand")';
        $.ajax({
            type: "POST",
            url: serviceUrl,
            dataType: 'json',
            data: { 'className': className },
            success: SetInitCommand,
            error: errorFunc
        });

        //serviceUrl = '/SmarTeam/GetDetailsCommand';
        serviceUrl = '@Url.Content("~/SmarTeam/GetDetailsCommand")';
        $.ajax({
            type: "POST",
            url: serviceUrl,
            dataType: 'json',
            data: { 'className': className },
            success: SetDetailsCommand,
            error: errorFunc
        });

        // Show dialog
        $('#myCommandModal').modal();
    }

    function SetInitCommand(data, status) {
        $('#initializationCommandTextBox').val(data);
    }
    function SetDetailsCommand(data, status) {
        $('#detailsCommandTextBox').val(data);
    }

    function showProcessClassModal(className) {
        $('#classHeaderBox').html(className);
        var configurationName = 'azzysa.ef.' + className.toLowerCase().replace(/ /g,'');
        $('#classMappingTextBox').val(configurationName);
        $('#ProcessClassModal').modal();
    }

    function ProcessClassAsync() {
        var className = $('#classHeaderBox').html();
        var mapping = $('#classMappingTextBox').val();
        var filterAttribute = $('#classFilterAttributeTextBox').val();
        var filterValue = $('#classFilterValueTextBox').val();

        // Invoke Web Api
        //var serviceUrl = '/SmarTeam/ProcessAsync';
        var serviceUrl = '@Url.Content("~/SmarTeam/ProcessAsync")';
        $.ajax({
            type: "POST",
            url: serviceUrl,
            dataType: 'json',
            data: { 'className': className, 'configurationName': mapping, 'filterAttribute': filterAttribute, 'filterValue': filterValue },
            success: ShowProcessResultFromClassAsync,
            error: errorFunc
        });
    }

    function showProcessPackageModal(className) {
        $('#myModalLabel').html(className);
        var configurationName = 'azzysa.ef.' + className.toLowerCase().replace(/ /g, '');
        $('#mappingTextBox').val(configurationName);
        $('#ProcessPackageModal').modal();
    }

    function ProcessPackageAsync() {
        var className = $('#myModalLabel').html();
        var packageId = $('#packageIdTextBox').val();
        var mapping = $('#mappingTextBox').val();

        // Invoke Web Api
        //var serviceUrl = '/SmarTeam/ProcessPackageAsync';
        var serviceUrl = '@Url.Content("~/SmarTeam/ProcessPackageAsync")';
        $.ajax({
            type: "POST",
            url: serviceUrl,
            dataType: 'json',
            data: { 'className': className, 'configurationName': mapping, 'packageId' : packageId },
            success: ShowProcessResultFromPackageAsync,
            error: errorFunc
        });
    }

    function showDownloadPackageModal(className) {
        $('#DownloadPackageLabel').html(className);
        $('#DownloadPackageModal').modal();
    }

    function DownloadPackageAsync() {
        var className = $('#DownloadPackageLabel').html();
        var packageId = $('#downloadPackageId').val();

        // Invoke Web Api
        //var serviceUrl = '/SmarTeam/DownloadPackage';
        var serviceUrl = '@Url.Content("~/SmarTeam/DownloadPackage")';
        $.fileDownload(serviceUrl, {
            httpMethod: "GET",
            data: { 'className': className, 'packageId': packageId, 'attributeFilter': '' },
            error: errorFunc
        });
    }

    function ShowProcessResultFromClassAsync(data, status) {
        var className = $('#classHeaderBox').html();
        $('#ProcessResultHeader').html(className);
        $('#ProcessResultMessage').html(data);
        $('#ProcessClassModal').modal('hide');
        $('#ProcessResultModal').modal();
    }

    function ShowProcessResultFromPackageAsync(data, status) {
        var className = $('#myModalLabel').html();
        $('#ProcessResultHeader').html(className);
        $('#ProcessResultMessage').html(data);
        $('#ProcessPackageModal').modal('hide');
        $('#ProcessResultModal').modal();
    }

    function errorFunc(xhr, status, error) {
        alert('An error has occured');
        alert(error);
        var err = eval("(" + xhr.responseText + ")");
        alert(err.Message);
    }

</script>

<!-- Modal -->
<div class="modal fade" id="ProcessResultModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
                <h4 id="ProcessResultHeader" style="color:darkgrey"></h4>
            </div>
            <div class="modal-body">
                <p style="color:darkgray" id="ProcessResultMessage"></p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-primary" data-dismiss="modal">OK</button>
            </div>
        </div>
    </div>
</div>
<div class="modal fade" id="ProcessPackageModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
                <h4 id="myModalLabel" style="color:darkgrey"></h4>
            </div>
            <div class="modal-body">
                <p style="color:darkgray">Mapping:</p>
                <p style="color:darkgray"><input type="text" id="mappingTextBox" class="text-primary" /></p>
                <p></p>
                <p style="color:darkgray">Package Id:</p>
                <p style="color:darkgray"><input type="text" id="packageIdTextBox" class="text-primary" /></p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-primary" data-dismiss="modal">Close</button>
                <button type="button" class="btn btn-primary" onclick="ProcessPackageAsync();">Start</button>
            </div>
        </div>
    </div>
</div>
<div class="modal fade" id="DownloadPackageModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
                <h4 id="DownloadPackageLabel" style="color:darkgrey"></h4>
            </div>
            <div class="modal-body">
                <p style="color:darkgray">Package Id:</p>
                <p style="color:darkgray"><input type="text" id="downloadPackageId" class="text-primary" /></p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-primary" data-dismiss="modal">Close</button>
                <button type="button" class="btn btn-primary" onclick="DownloadPackageAsync();">Download</button>
            </div>
        </div>
    </div>
</div>
<div class="modal fade" id="ProcessClassModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
                <h4 id="classHeaderBox" style="color:darkgrey"></h4>
            </div>
            <div class="modal-body">
                <p style="color:darkgray">Mapping:</p>
                <p style="color:darkgray"><input type="text" id="classMappingTextBox" class="text-primary" /></p>
                <p></p>
                <p style="color:darkgray">Filter attribute:</p>
                <p style="color:darkgray"><input type="text" id="classFilterAttributeTextBox" class="text-primary" /></p>
                <p></p>
                <p style="color:darkgray">Filter value:</p>
                <p style="color:darkgray"><input type="text" id="classFilterValueTextBox" class="text-primary" /></p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-primary" data-dismiss="modal">Close</button>
                <button type="button" class="btn btn-primary" onclick="ProcessClassAsync();">Start</button>
            </div>
        </div>
    </div>
</div>
<div class="modal fade" id="myCommandModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
                <h4 id="CommandModalLabel" style="color:darkgrey"></h4>
            </div>
            <div class="modal-body">
                <p><textarea id="initializationCommandTextBox" class="text-primary" cols="90" rows="2"></textarea></p>
                <p><textarea id="detailsCommandTextBox" class="text-primary" cols="90" rows="15"></textarea></p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-primary" data-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>

@foreach (var item in Model)
{
    <div class="col-md-3 col-sm-6">
        <div class="service-item">
            <span class="fa-stack fa-4x">
                <i class="fa fa-circle fa-stack-2x"></i>
                <i class="fa fa-cloud fa-stack-1x text-primary"></i>
            </span>
            <h4>
                <strong>@item.Name</strong>
            </h4>
            <p>@Html.TextBox(@item.Name.Replace(" ", "") + "_ConfigurationName", "azzysa.ef." + item.Name.ToLower().Replace(" ", string.Empty), new { Style = "background:#cccccc;" })</p>
            <p><button type="button" class="btn btn-primary btn-lg" onclick="ShowCommands('@item.Name');">Commands</button></p>
            <p><button type="button" class="btn btn-primary btn-lg" onclick="showDownloadPackageModal('@item.Name');">Download Package</button></p>
            <p><button type="button" class="btn btn-primary btn-lg" onclick="showProcessPackageModal('@item.Name');">Process Package</button></p>
            <p><button type="button" class="btn btn-primary btn-lg" onclick="showProcessClassModal('@item.Name');">Process Class</button></p>
</div>
    </div>
}

Infostrait.Azzysa.Import.UI/Views/SmarTeam/Process.cshtml
@{
    ViewBag.Title = "Migration started";
}

<h2>Migration process has been started!</h2>